import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ModeToggle } from '~/components/mode-toggle';
import { SidebarInset, SidebarTrigger } from '~/components/ui/sidebar';

import { AppSidebar } from '~/components/app-sidebar';
import './globals.css';
import Providers from './providers';
import Github from '~/components/github';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'OpenPix 🎈 - Image Editor',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Audiowide&family=BBH+Sans+Bartle&family=BBH+Sans+Bogle&family=BBH+Sans+Hegarty&family=Borel&family=Delius+Unicase:wght@400;700&family=Doto:wght@100..900&family=Iceland&family=Meow+Script&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Pacifico&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Playwrite+DE+SAS:wght@100..400&family=Quicksand:wght@300..700&family=Roboto:ital,wght@0,100..900;1,100..900&family=Sour+Gummy:ital,wght@0,100..900;1,100..900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&family=UnifrakturMaguntia&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppSidebar />
          <SidebarInset className="relative flex-1 min-h-svh">
            {/* Navbar */}
            <nav className="flex items-start justify-between bg-card ">
              <SidebarTrigger className="cursor-pointer m-1 backdrop-blur-3xl" />
              <div className="p-1 flex items-center gap-2">
                {/* Github Link */}
                <Github />

                {/* Dark/Light */}
                <ModeToggle />

                {/* Export Options */}
                <div id="export-portal" />
              </div>
            </nav>
            {/* Content */}
            {children}
          </SidebarInset>
        </Providers>
      </body>
    </html>
  );
}
