import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { AppSidebar } from '~/components/app-sidebar';
import { ModeToggle } from '~/components/mode-toggle';
import { ThemeProvider } from '~/components/theme-provider';
import { SidebarProvider, SidebarTrigger } from '~/components/ui/sidebar';
import { FiltersProvider } from '~/components/filters-context';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <SidebarProvider>
            <FiltersProvider>
              <AppSidebar />
              <main className="relative flex-1 min-h-svh">
              {/* Navbar */}
              <nav className="flex items-start justify-between absolute top-0 z-10 right-0 left-0">
                <SidebarTrigger className="cursor-pointer m-1 backdrop-blur-3xl" />
                <div className="p-1">
                  <ModeToggle />
                </div>
              </nav>
              {/* Content */}
              {children}
              </main>
            </FiltersProvider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
